ALTER TABLE users ADD COLUMN IF NOT EXISTS gender ENUM('Male', 'Female', 'Other') AFTER name;
ALTER TABLE users ADD COLUMN IF NOT EXISTS mobile VARCHAR(15) AFTER email;
ALTER TABLE users ADD COLUMN IF NOT EXISTS dob DATE AFTER mobile;
ALTER TABLE users ADD COLUMN IF NOT EXISTS admission_type VARCHAR(50) AFTER batch;
